# Generated by Django 3.0.5 on 2021-02-25 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('classes_id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('class_name', models.CharField(db_column='class_name', max_length=100)),
                ('information', models.TextField(db_column='information')),
            ],
            options={
                'db_table': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Meteorite',
            fields=[
                ('meteorite_id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('mass', models.FloatField(db_column='mass (g)')),
                ('fall', models.CharField(db_column='fall', max_length=10)),
                ('year', models.DateField(db_column='year')),
                ('reclat', models.FloatField(db_column='reclat')),
                ('reclong', models.FloatField(db_column='reclong')),
                ('geoLocation', models.CharField(db_column='GeoLocation', max_length=100)),
                ('recclass_id', models.ForeignKey(db_column='recclass_id', on_delete=django.db.models.deletion.CASCADE, to='meteorites.Classes')),
            ],
            options={
                'db_table': 'Meteorites',
            },
        ),
    ]
