# Generated by Django 3.0.5 on 2021-03-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Класс метеорита', 'verbose_name_plural': 'Классы метеоритов'},
        ),
        migrations.AlterModelOptions(
            name='meteorite',
            options={'verbose_name': 'Метеорит', 'verbose_name_plural': 'Метеориты'},
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_name',
            field=models.CharField(db_column='class_name', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='classes_id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='information',
            field=models.TextField(db_column='information', verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='meteorite',
            name='fall',
            field=models.CharField(db_column='fall', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='meteorite',
            name='geoLocation',
            field=models.CharField(db_column='GeoLocation', max_length=100, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='meteorite',
            name='mass',
            field=models.FloatField(db_column='mass (g)', verbose_name='Масса'),
        ),
        migrations.AlterField(
            model_name='meteorite',
            name='meteorite_id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='meteorite',
            name='name',
            field=models.CharField(db_column='name', max_length=100, verbose_name='Название метеорита'),
        ),
        migrations.AlterField(
            model_name='meteorite',
            name='reclat',
            field=models.FloatField(db_column='reclat', verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='meteorite',
            name='reclong',
            field=models.FloatField(db_column='reclong', verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='meteorite',
            name='year',
            field=models.DateField(db_column='year', verbose_name='Дата'),
        ),
    ]
