# Generated by Django 3.0.5 on 2021-03-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteorites', '0002_auto_20210301_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='classes_id',
            field=models.AutoField(db_column='id', default=0, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
